name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd api
          npm install

      - name: Run lint
        run: |
          cd api
          npm run lint
        continue-on-error: false

      - name: Run format check
        run: |
          cd api
          npm run format:check
        continue-on-error: false

      - name: Run tests
        run: |
          cd api
          npm test
        continue-on-error: false
